server.port=8090
spring.application.name=spring-ai-chat-mcp-client
spring.ai.openai.api-key=${DEEPSEEK_API_KEY:default}
spring.ai.openai.chat.base-url=https://api.deepseek.com
spring.ai.openai.chat.options.model=deepseek-reasoner

spring.ai.mcp.client.toolcallback.enabled=true
# sse (Server-Sent Events) \u65B9\u5F0F
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.sse.connections.general-mcp-server.url=http://localhost:8100
spring.ai.mcp.client.sse.connections.general-mcp-server.sse-endpoint=/tools
spring.ai.mcp.client.request-timeout=30000
spring.ai.mcp.client.type=async

logging.level.springai.http=DEBUG
